name: Block vNext merges into develoop

on:
  pull_request:
    branches:    
      - develop
    types:
      - opened
      - synchronize

jobs:
  check-commits:
    runs-on: ils

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: fetch
        run: git fetch

      - name: Check if target branch contains 'feature'
        run: |
          target_branch=$(echo "${{ github.event.pull_request.base.ref }}" | tr '[:upper:]' '[:lower:]')
          if [[ $target_branch == *"feature"* ]]; then
            echo "Target branch contains 'feature'. Proceeding with checks."
          else
            echo "Target branch does not contain 'feature'. Exiting workflow."
            exit 0
          fi

      - name: Get list of vnext branches
        id: get-branches
        run: |
          branches=$(git branch -r | grep 'origin/vnext/*' | sed 's/origin\///')
          echo "::set-output name=branches::$branches"

      - name: Check commit hashes
        id: check-commits
        run: |
          branches="${{ steps.get-branches.outputs.branches }}"
          commit_hashes=$(git log --pretty=format:"%H" ${{ github.event.pull_request.base.sha }}^..${{ github.event.pull_request.head.sha }})
          for hash in $commit_hashes; do
            for branch in $branches; do
              echo "Checking: $hash in $branch"
              if git merge-base --is-ancestor $hash origin/$branch; then
                echo "Error: Commit hash $hash found in branch $branch"
                exit 1
              fi
            done
          done
          echo "All commit hashes are valid."

      - name: Echo success message
        if: steps.check-commits.outcome == 'success'
        run: echo "Workflow completed successfully."
