name: Check Feature Branch Origin

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-branch-origin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get common ancestor commit
        id: merge-base
        run: echo "::set-output name=commit::$(git merge-base ${{ github.base_ref }} ${{ github.head_ref }})"

      - name: Verify branch origin
        run: |
          common_ancestor_commit="${{ steps.merge-base.outputs.commit }}"
          first_commit_in_feature_branch=$(git rev-list --max-parents=0 HEAD)

          if [ "$common_ancestor_commit" != "$first_commit_in_feature_branch" ]; then
            echo "Error: Feature branch was not created from master."
            exit 1
          fi
